sudo: required
services:
  - docker

before_install:
  - docker build -t ryanmiranda98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryanmiranda98/react-test npm test

after_success:
  - docker build -t ryanmiranda98/multi-client ./client
  - docker build -t ryanmiranda98/multi-server ./server
  - docker build -t ryanmiranda98/multi-nginx ./nginx
  - docker build -t ryanmiranda98/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push to docker hub
  - docker push ryanmiranda98/multi-client
  - docker push ryanmiranda98/multi-server
  - docker push ryanmiranda98/multi-nginx
  - docker push ryanmiranda98/multi-worker
